/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hospital;

import classes.DbHelper;
import classes.Department;
import classes.Doctor;
import java.awt.Image;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DUMAN
 */
public class DepartmentGUI extends javax.swing.JFrame {

    /**
     * Creates new form DepartmentGUI
     */
    DefaultTableModel modelBolumler;
    DefaultTableModel modelDoktorlar;
    String bolumId;

    public DepartmentGUI() {
        initComponents();
        modelBolumler = (DefaultTableModel) tblBolumler.getModel();
        modelDoktorlar = (DefaultTableModel) tblDoktorlar.getModel();
        loadDataBolum();
        PatientGUI patient = new PatientGUI();
        patient.resimDuzelt(lblCarpi, "Images/carpiIcon.png");
    }

    private void loadDataBolum() {
        modelBolumler.setRowCount(0);
        try {
            ArrayList<Department> departments = getDepartments();
            for (Department department : departments) {
                Object[] row = {department.getBolum()};
                modelBolumler.addRow(row);
            }
        } catch (SQLException ex) {

        }
    }

    private void loadDataDoctor() {
        modelDoktorlar.setRowCount(0);
        try {
            ArrayList<Doctor> doctors = getDoctors();
            for (Doctor doctor : doctors) {
                Object[] row = {doctor.getAd(), doctor.getSoyad(), doctor.getCinsiyet(), doctor.getTelefon(), doctor.getEmail()};
                modelDoktorlar.addRow(row);
            }
        } catch (SQLException ex) {
        }
    }

    public ArrayList<Doctor> getDoctors() throws SQLException {
        Connection connection = null;
        DbHelper helper = new DbHelper();
        Statement statement = null;
        ResultSet resultSet;
        ArrayList<Doctor> doctors = null;
        try {
            connection = helper.getConnection();
            statement = connection.createStatement();
            resultSet = statement.executeQuery("select * from doktorlar where bolum_id = " + bolumId);
            doctors = new ArrayList<Doctor>();
            while (resultSet.next()) {
                doctors.add(new Doctor(
                        resultSet.getInt("id"),
                        resultSet.getString("tc_kimlik"),
                        resultSet.getString("ad"),
                        resultSet.getString("soyad"),
                        resultSet.getString("dogum_tarihi"),
                        resultSet.getString("cinsiyet"),
                        resultSet.getString("telefon"),
                        resultSet.getString("email"),
                        resultSet.getString("adres"), resultSet.getInt("bolum_id")));
            }
        } catch (SQLException e) {
            helper.showErrorMessage(e);
        } finally {
            statement.close();
            connection.close();
        }
        return doctors;
    }

    public ArrayList<Department> getDepartments() throws SQLException {
        Connection connection = null;
        DbHelper helper = new DbHelper();
        Statement statement = null;
        ResultSet resultSet;
        ArrayList<Department> departments = null;
        try {
            connection = helper.getConnection();
            statement = connection.createStatement();
            resultSet = statement.executeQuery("select * from bolumler");
            departments = new ArrayList<Department>();
            while (resultSet.next()) {
                departments.add(new Department(
                        resultSet.getInt("id"),
                        resultSet.getString("bolum_adi")));
            }
        } catch (SQLException e) {
            helper.showErrorMessage(e);
        } finally {
            statement.close();
            connection.close();
        }
        return departments;
    }

    public void resimDuzelt(JLabel label, String url) {
        ImageIcon icon = new ImageIcon(getClass().getResource("/" + url));
        Image resim = icon.getImage();
        Image yeniResim = resim.getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon yeniIcon = new ImageIcon(yeniResim);
        label.setIcon(yeniIcon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDoktorlar = new javax.swing.JTable();
        lblHastaBilgileri = new javax.swing.JLabel();
        lblCizgi = new javax.swing.JLabel();
        lblBolumAdi = new javax.swing.JLabel();
        lblBolumNo = new javax.swing.JLabel();
        btnBolumNo = new javax.swing.JButton();
        txtBolumAdi = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblBolumler = new javax.swing.JTable();
        btnGuncelle = new javax.swing.JButton();
        btnEkle = new javax.swing.JButton();
        btnSil = new javax.swing.JButton();
        lblCarpi = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bölüm Bilgileri");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        tblDoktorlar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ad", "Soyad", "Cinsiyet", "Telefon", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDoktorlar.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblDoktorlar);
        if (tblDoktorlar.getColumnModel().getColumnCount() > 0) {
            tblDoktorlar.getColumnModel().getColumn(0).setResizable(false);
            tblDoktorlar.getColumnModel().getColumn(1).setResizable(false);
            tblDoktorlar.getColumnModel().getColumn(2).setResizable(false);
            tblDoktorlar.getColumnModel().getColumn(3).setResizable(false);
            tblDoktorlar.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 600, 210));

        lblHastaBilgileri.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblHastaBilgileri.setText("Bölüm Bilgileri");
        jPanel1.add(lblHastaBilgileri, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        lblCizgi.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblCizgi.setText("__________________");
        jPanel1.add(lblCizgi, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        lblBolumAdi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBolumAdi.setText("Bölüm Adı:");
        jPanel1.add(lblBolumAdi, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        lblBolumNo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBolumNo.setText("Bölüm No:");
        jPanel1.add(lblBolumNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        btnBolumNo.setEnabled(false);
        jPanel1.add(btnBolumNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 100, 70, 25));
        jPanel1.add(txtBolumAdi, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 180, 30));

        jScrollPane2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        tblBolumler.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tblBolumler.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BÖLÜMLER"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblBolumler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBolumlerMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblBolumler);
        if (tblBolumler.getColumnModel().getColumnCount() > 0) {
            tblBolumler.getColumnModel().getColumn(0).setResizable(false);
        }

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 330, 220));

        btnGuncelle.setText("GÜNCELLE");
        btnGuncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuncelleActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuncelle, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 240, 90, 25));

        btnEkle.setText("EKLE");
        btnEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEkleActionPerformed(evt);
            }
        });
        jPanel1.add(btnEkle, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 240, 75, 25));

        btnSil.setText("SİL");
        btnSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSilActionPerformed(evt);
            }
        });
        jPanel1.add(btnSil, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 240, 75, 25));

        lblCarpi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCarpi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCarpiMouseClicked(evt);
            }
        });
        jPanel1.add(lblCarpi, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 30, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 520));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tblBolumlerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBolumlerMouseClicked
        // TODO add your handling code here:
        Connection connection = null;
        DbHelper dbHelper = new DbHelper();
        PreparedStatement statement = null;
        ResultSet result;
        try {
            connection = dbHelper.getConnection();
            String sql = "select * from bolumler where bolum_adi = ?";
            statement = connection.prepareStatement(sql);
            String bolum_adi = (String) tblBolumler.getValueAt(tblBolumler.getSelectedRow(), 0);
            statement.setString(1, bolum_adi);
            result = statement.executeQuery();
            if (result.next()) {
                bolumId = result.getString("id");
                btnBolumNo.setText(bolumId);
                txtBolumAdi.setText((String) tblBolumler.getValueAt(tblBolumler.getSelectedRow(), 0));
                loadDataDoctor();
            }
        } catch (SQLException e) {
            dbHelper.showErrorMessage(e);
        } finally {
            try {
                connection.close();
                statement.close();
            } catch (SQLException ex) {
            }
        }
    }//GEN-LAST:event_tblBolumlerMouseClicked

    private void btnEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEkleActionPerformed
        // TODO add your handling code here:
        Connection connection = null;
        DbHelper dbHelper = new DbHelper();
        PreparedStatement statement = null;
        if (!txtBolumAdi.getText().equals("")) {
            try {
                connection = dbHelper.getConnection();
                String sql = "INSERT INTO bolumler (bolum_adi) VALUES (?)";
                String bolumAdi = txtBolumAdi.getText().substring(0,1).toUpperCase()+txtBolumAdi.getText().substring(1);
                statement = connection.prepareStatement(sql);
                statement.setString(1, bolumAdi);
                statement.executeUpdate();
                JOptionPane.showMessageDialog(rootPane, "Kayıt İşlemi Başarılı!");
                loadDataBolum();
            } catch (SQLException e) {
                dbHelper.showErrorMessage(e);
            } finally {
                try {
                    connection.close();
                    statement.close();
                } catch (SQLException ex) {
                }
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Bölüm Adı Giriniz!");
        }
    }//GEN-LAST:event_btnEkleActionPerformed

    private void btnSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSilActionPerformed
        // TODO add your handling code here:
        Connection connection = null;
        DbHelper dbHelper = new DbHelper();
        PreparedStatement statement = null;
        if (tblBolumler.getSelectedRow() != -1) {
            try {
                connection = dbHelper.getConnection();
                String sql = "delete from bolumler where id = "+bolumId;
                statement = connection.prepareStatement(sql);
                statement.executeUpdate();
                JOptionPane.showMessageDialog(rootPane, "Silme İşlemi Başarılı!");
                loadDataBolum();
            } catch (SQLException e) {
                dbHelper.showErrorMessage(e);
            } finally {
                try {
                    connection.close();
                    statement.close();
                } catch (SQLException ex) {
                }
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "Silmek İstediğiniz Bölümü Seçiniz!");
        }
    }//GEN-LAST:event_btnSilActionPerformed

    private void btnGuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuncelleActionPerformed
        // TODO add your handling code here:
        Connection connection = null;
        DbHelper dbHelper = new DbHelper();
        PreparedStatement statement = null;
        if (!txtBolumAdi.getText().equals("")) {
            try {
                connection = dbHelper.getConnection();
                String sql = "update bolumler set bolum_adi = ? where id = "+bolumId;
                statement = connection.prepareStatement(sql);
                String bolumAdi = txtBolumAdi.getText().substring(0,1).toUpperCase()+txtBolumAdi.getText().substring(1);
                statement.setString(1, bolumAdi);
                statement.executeUpdate();
                JOptionPane.showMessageDialog(rootPane, "Güncelleme İşlemi Başarılı!");
                loadDataBolum();
            } catch (SQLException e) {
                dbHelper.showErrorMessage(e);
            } finally {
                try {
                    connection.close();
                    statement.close();
                } catch (SQLException ex) {
                }
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "Bölüm Adı Giriniz!");
        }
    }//GEN-LAST:event_btnGuncelleActionPerformed

    private void lblCarpiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCarpiMouseClicked
        // TODO add your handling code here:
        MenuGUI menu = new MenuGUI();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblCarpiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DepartmentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DepartmentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DepartmentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DepartmentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DepartmentGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBolumNo;
    private javax.swing.JButton btnEkle;
    private javax.swing.JButton btnGuncelle;
    private javax.swing.JButton btnSil;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBolumAdi;
    private javax.swing.JLabel lblBolumNo;
    private javax.swing.JLabel lblCarpi;
    private javax.swing.JLabel lblCizgi;
    private javax.swing.JLabel lblHastaBilgileri;
    private javax.swing.JTable tblBolumler;
    private javax.swing.JTable tblDoktorlar;
    private javax.swing.JTextField txtBolumAdi;
    // End of variables declaration//GEN-END:variables
}
