/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hospital;

import classes.DbHelper;
import java.sql.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.util.Date;

/**
 *
 * @author DUMAN
 */
public class LoginGUI extends javax.swing.JFrame {

    /**
     * Creates new form LoginGUI
     */
    int userId = 1;
    public LoginGUI() {
        initComponents();
    }
    
    public String formattedDate(String newDate){
        String formattedDate = "";
        SimpleDateFormat inputFormat = new SimpleDateFormat("dd-MM-yyyy");
        SimpleDateFormat outputFormat = new SimpleDateFormat("yyyy-MM-dd");
        Date date;
        try {
            date = inputFormat.parse(newDate);
            formattedDate = outputFormat.format(date);
        } catch (ParseException ex) {
            System.out.println("Hata: Geçersiz tarih formatı!");
        }
        return formattedDate;
    }
    
    public String formattedDate(Date newDate){
        String formattedDate = "";
        SimpleDateFormat outputFormat = new SimpleDateFormat("yyyy-MM-dd");
        formattedDate = outputFormat.format(newDate);
        return formattedDate;
    }
    
    public String getirFormattedDate(String newDate){
        String formattedDate = "";
        SimpleDateFormat inputFormat = new SimpleDateFormat("yyyy-MM-dd");
        SimpleDateFormat outputFormat = new SimpleDateFormat("dd-MM-yyyy");
        Date date;
        try {
            date = inputFormat.parse(newDate);

            formattedDate = outputFormat.format(date);
        } catch (ParseException ex) {
            System.out.println("Hata: Geçersiz tarih formatı!");
        }
        return formattedDate;
    }

    private boolean checkLogin() {
        boolean isValid = false;
        char[] password = pswSifre.getPassword();
        String stringPassword = new String(password);
        if (stringPassword.equals("") || txtKullaniciAdi.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Tüm Alanları Doldurunuz");
            return isValid;
        }
        Connection connection = null;
        DbHelper dbHelper = new DbHelper();
        PreparedStatement statement = null;
        ResultSet result;
        try {
            connection = dbHelper.getConnection();
            String sql = "select * from kullanicilar where tc_kimlik = ?";
            statement = connection.prepareStatement(sql);
            statement.setString(1, txtKullaniciAdi.getText());
            result = statement.executeQuery();
            if (result.next()) {
                if (result.getInt("hatali_giris") == 3) {
                    JOptionPane.showMessageDialog(rootPane, "Şifre Bloke Olmuştur Sistem Yöneticinize Başvurun");
                } else if (result.getString("sifre").equals(stringPassword)) {
                    isValid = true;
                    userId = result.getInt("id");
                    sql = "update kullanicilar set hatali_giris = 0 where tc_kimlik = ?";
                    statement = connection.prepareStatement(sql);
                    statement.setString(1, txtKullaniciAdi.getText());
                    statement.executeUpdate();
                } else {
                    sql = "update kullanicilar set hatali_giris = hatali_giris+1 where tc_kimlik = ?";
                    statement = connection.prepareStatement(sql);
                    statement.setString(1, txtKullaniciAdi.getText());
                    statement.executeUpdate();
                    JOptionPane.showMessageDialog(rootPane, "Kullanıcı Şifresi Yanlış");
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Kullanıcı Bulunamadı");
            }

        } catch (SQLException e) {
            dbHelper.showErrorMessage(e);
        } finally {
            try {
                statement.close();
                connection.close();
            } catch (SQLException ex) {
            }
        }

        return isValid;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlResim = new javax.swing.JPanel();
        lblLoginResim = new javax.swing.JLabel();
        pnlLogin = new javax.swing.JPanel();
        txtKullaniciAdi = new javax.swing.JTextField();
        btnKayit = new javax.swing.JButton();
        btnGiris = new javax.swing.JButton();
        lblKullaniciAdi = new javax.swing.JLabel();
        lblSifre = new javax.swing.JLabel();
        pswSifre = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlResim.setBackground(new java.awt.Color(255, 255, 255));

        lblLoginResim.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLoginResim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/images.jpeg"))); // NOI18N

        javax.swing.GroupLayout pnlResimLayout = new javax.swing.GroupLayout(pnlResim);
        pnlResim.setLayout(pnlResimLayout);
        pnlResimLayout.setHorizontalGroup(
            pnlResimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlResimLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLoginResim, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlResimLayout.setVerticalGroup(
            pnlResimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResimLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLoginResim, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(pnlResim, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 0, 260, 391));

        pnlLogin.setBackground(new java.awt.Color(255, 255, 255));

        txtKullaniciAdi.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtKullaniciAdi.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        btnKayit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnKayit.setText("KAYIT OL");
        btnKayit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKayitActionPerformed(evt);
            }
        });

        btnGiris.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGiris.setText("GİRİŞ YAP");
        btnGiris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGirisActionPerformed(evt);
            }
        });

        lblKullaniciAdi.setFont(new java.awt.Font("Monotype Corsiva", 3, 16)); // NOI18N
        lblKullaniciAdi.setText("TC Kimlik Numarası:");

        lblSifre.setFont(new java.awt.Font("Monotype Corsiva", 3, 16)); // NOI18N
        lblSifre.setText("Şifre:");

        javax.swing.GroupLayout pnlLoginLayout = new javax.swing.GroupLayout(pnlLogin);
        pnlLogin.setLayout(pnlLoginLayout);
        pnlLoginLayout.setHorizontalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pswSifre, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlLoginLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(btnGiris, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnKayit, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblSifre, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKullaniciAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKullaniciAdi))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        pnlLoginLayout.setVerticalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginLayout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addComponent(lblKullaniciAdi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtKullaniciAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(lblSifre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pswSifre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGiris, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKayit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(104, 104, 104))
        );

        getContentPane().add(pnlLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnKayitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKayitActionPerformed
        NewUserGUI user = new NewUserGUI();
        this.setVisible(false);
        user.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKayitActionPerformed

    private void btnGirisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGirisActionPerformed
        // TODO add your handling code here:
        if (checkLogin()) {
            MenuGUI menu = new MenuGUI();
            menu.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnGirisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGiris;
    private javax.swing.JButton btnKayit;
    private javax.swing.JLabel lblKullaniciAdi;
    private javax.swing.JLabel lblLoginResim;
    private javax.swing.JLabel lblSifre;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JPanel pnlResim;
    private javax.swing.JPasswordField pswSifre;
    private javax.swing.JTextField txtKullaniciAdi;
    // End of variables declaration//GEN-END:variables
}
