/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hospital;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author DUMAN
 */
public class MenuGUI extends javax.swing.JFrame {

    /**
     * Creates new form MenuGUI
     */
    
    public MenuGUI() {
        initComponents();
        resimDuzelt(lblResim, "Images/menuResim.png");
        resimDuzelt(lblDoctorIcon, "Images/doktorMenu.png");
        resimDuzelt(lblRandevuIcon, "Images/randevuMenu.png");
        resimDuzelt(lblHastaIcon, "Images/hastaMenu.png");
        resimDuzelt(lblRaporIcon, "Images/raporMenu.png");
        resimDuzelt(lblBolumIcon, "Images/bolumMenu.png");
        resimDuzelt(lblGeriDonIcon, "Images/backIcon.png");
    }
    
    public void resimDuzelt(JLabel label, String url){
        ImageIcon icon = new ImageIcon(getClass().getResource("/"+url));
        Image resim = icon.getImage();
        Image yeniResim = resim.getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon yeniIcon = new ImageIcon(yeniResim);
        label.setIcon(yeniIcon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblResim = new javax.swing.JLabel();
        pnlDoktor = new javax.swing.JPanel();
        lblDoktorBilgileri = new javax.swing.JLabel();
        lblDoctorIcon = new javax.swing.JLabel();
        pnlRandevu = new javax.swing.JPanel();
        lblRandevuBilgileri = new javax.swing.JLabel();
        lblRandevuIcon = new javax.swing.JLabel();
        pnlBolum = new javax.swing.JPanel();
        lblBolumIcon = new javax.swing.JLabel();
        lblBolumBilgileri = new javax.swing.JLabel();
        pnlHasta = new javax.swing.JPanel();
        lblHastaBilgileri = new javax.swing.JLabel();
        lblHastaIcon = new javax.swing.JLabel();
        pnlRapor = new javax.swing.JPanel();
        lblRaporBilgileri = new javax.swing.JLabel();
        lblRaporIcon = new javax.swing.JLabel();
        pnlGeriDon = new javax.swing.JPanel();
        lblGeriDonIcon = new javax.swing.JLabel();
        lblGeriDon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hastane Menü");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(lblResim, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 310, 510));

        pnlDoktor.setBackground(new java.awt.Color(255, 255, 255));
        pnlDoktor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        pnlDoktor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlDoktor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlDoktorMouseClicked(evt);
            }
        });
        pnlDoktor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDoktorBilgileri.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDoktorBilgileri.setText("Doktor Bilgileri");
        pnlDoktor.add(lblDoktorBilgileri, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 120, 104, -1));
        pnlDoktor.add(lblDoctorIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 10, 100, 100));

        jPanel1.add(pnlDoktor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 150, 150));

        pnlRandevu.setBackground(new java.awt.Color(255, 255, 255));
        pnlRandevu.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        pnlRandevu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlRandevu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlRandevuMouseClicked(evt);
            }
        });
        pnlRandevu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRandevuBilgileri.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblRandevuBilgileri.setText("Randevu Bilgileri");
        pnlRandevu.add(lblRandevuBilgileri, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 120, 116, -1));
        pnlRandevu.add(lblRandevuIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 10, 100, 100));

        jPanel1.add(pnlRandevu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 150, 150));

        pnlBolum.setBackground(new java.awt.Color(255, 255, 255));
        pnlBolum.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        pnlBolum.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlBolum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlBolumMouseClicked(evt);
            }
        });
        pnlBolum.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlBolum.add(lblBolumIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 10, 100, 100));

        lblBolumBilgileri.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBolumBilgileri.setText("Bölüm Bilgileri");
        pnlBolum.add(lblBolumBilgileri, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 120, -1, -1));

        jPanel1.add(pnlBolum, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 150, 150));

        pnlHasta.setBackground(new java.awt.Color(255, 255, 255));
        pnlHasta.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        pnlHasta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlHasta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlHastaMouseClicked(evt);
            }
        });
        pnlHasta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHastaBilgileri.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblHastaBilgileri.setText("Hasta Bilgileri");
        pnlHasta.add(lblHastaBilgileri, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 120, 96, -1));
        pnlHasta.add(lblHastaIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 10, 100, 100));

        jPanel1.add(pnlHasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 150, 150));

        pnlRapor.setBackground(new java.awt.Color(255, 255, 255));
        pnlRapor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        pnlRapor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlRapor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlRaporMouseClicked(evt);
            }
        });
        pnlRapor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRaporBilgileri.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblRaporBilgileri.setText("Rapor Bilgileri");
        pnlRapor.add(lblRaporBilgileri, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 120, 98, -1));
        pnlRapor.add(lblRaporIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 10, 100, 100));

        jPanel1.add(pnlRapor, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 150, 150));

        pnlGeriDon.setBackground(new java.awt.Color(255, 255, 255));
        pnlGeriDon.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        pnlGeriDon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlGeriDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlGeriDonMouseClicked(evt);
            }
        });
        pnlGeriDon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlGeriDon.add(lblGeriDonIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 10, 100, 100));

        lblGeriDon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblGeriDon.setText("Geri Dön");
        pnlGeriDon.add(lblGeriDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 120, 60, -1));

        jPanel1.add(pnlGeriDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, 150, 150));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pnlHastaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlHastaMouseClicked
        // TODO add your handling code here:
        PatientGUI patient = new PatientGUI();
        this.setVisible(false);
        patient.setVisible(true);
    }//GEN-LAST:event_pnlHastaMouseClicked

    private void pnlDoktorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDoktorMouseClicked
        // TODO add your handling code here:
        DoctorGUI doctor = new DoctorGUI();
        doctor.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_pnlDoktorMouseClicked

    private void pnlRandevuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlRandevuMouseClicked
        // TODO add your handling code here:
        AppointmentGUI appointment = new AppointmentGUI();
        appointment.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_pnlRandevuMouseClicked

    private void pnlBolumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBolumMouseClicked
        // TODO add your handling code here:
        DepartmentGUI department = new DepartmentGUI();
        department.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_pnlBolumMouseClicked

    private void pnlRaporMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlRaporMouseClicked
        // TODO add your handling code here:
        ReportGUI report = new ReportGUI();
        report.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_pnlRaporMouseClicked

    private void pnlGeriDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlGeriDonMouseClicked
        // TODO add your handling code here:
        LoginGUI login = new LoginGUI();
        login.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_pnlGeriDonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBolumBilgileri;
    private javax.swing.JLabel lblBolumIcon;
    private javax.swing.JLabel lblDoctorIcon;
    private javax.swing.JLabel lblDoktorBilgileri;
    private javax.swing.JLabel lblGeriDon;
    private javax.swing.JLabel lblGeriDonIcon;
    private javax.swing.JLabel lblHastaBilgileri;
    private javax.swing.JLabel lblHastaIcon;
    private javax.swing.JLabel lblRandevuBilgileri;
    private javax.swing.JLabel lblRandevuIcon;
    private javax.swing.JLabel lblRaporBilgileri;
    private javax.swing.JLabel lblRaporIcon;
    private javax.swing.JLabel lblResim;
    private javax.swing.JPanel pnlBolum;
    private javax.swing.JPanel pnlDoktor;
    private javax.swing.JPanel pnlGeriDon;
    private javax.swing.JPanel pnlHasta;
    private javax.swing.JPanel pnlRandevu;
    private javax.swing.JPanel pnlRapor;
    // End of variables declaration//GEN-END:variables
}
