/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hospital;

import classes.DbHelper;
import java.sql.*;
import java.awt.Image;
import java.util.Arrays;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author DUMAN
 */
public class NewUserGUI extends javax.swing.JFrame {

    /**
     * Creates new form NewUserGUI
     */
    LoginGUI login = new LoginGUI();
    
    public NewUserGUI() {
        initComponents();
        resimDuzelt(lblResim, "Images/userIcon.jpg");
        resimDuzelt(lblCarpi, "Images/carpiIcon.png");
        ButtonGroup group = new ButtonGroup();
        group.add(rdbErkek);
        group.add(rdbKadin);
    }

    public void resimDuzelt(JLabel label, String url) {
        ImageIcon icon = new ImageIcon(getClass().getResource("/" + url));
        Image resim = icon.getImage();
        Image yeniResim = resim.getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon yeni = new ImageIcon(yeniResim);
        label.setIcon(yeni);
    }

    public boolean kontrol() {
        boolean control = false;
        char[] password1 = pswSifre.getPassword();
        char[] password2 = pswSifreTekrar.getPassword();
        if (!ftxtTC.getText().isEmpty()
                && !ftxtTelefon.getText().isEmpty()
                && !ftxtDogumTarihi.getText().isEmpty()
                && !txtAd.getText().isEmpty()
                && !txtSoyad.getText().isEmpty()
                && !txtEmail.getText().isEmpty()
                && !txtaAdres.getText().isEmpty()
                && pswSifre.getPassword().length != 0
                && pswSifreTekrar.getPassword().length != 0
                && (rdbErkek.isSelected() || rdbKadin.isSelected())) {
            if (Arrays.equals(password1, password2)) {
                control = true;
            }
        }
        return control;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblResim = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblCarpi = new javax.swing.JLabel();
        lblKullaniciKayit = new javax.swing.JLabel();
        lblTC = new javax.swing.JLabel();
        lblCizgi = new javax.swing.JLabel();
        txtAd = new javax.swing.JTextField();
        lblAd = new javax.swing.JLabel();
        txtSoyad = new javax.swing.JTextField();
        lblSifre = new javax.swing.JLabel();
        lblDogumTarihi = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblCinsiyet = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        rdbErkek = new javax.swing.JRadioButton();
        rdbKadin = new javax.swing.JRadioButton();
        lblSoyad = new javax.swing.JLabel();
        pswSifre = new javax.swing.JPasswordField();
        pswSifreTekrar = new javax.swing.JPasswordField();
        lblAdres = new javax.swing.JLabel();
        btnTemizle = new javax.swing.JButton();
        btnKaydet = new javax.swing.JButton();
        ftxtTC = new javax.swing.JFormattedTextField();
        ftxtDogumTarihi = new javax.swing.JFormattedTextField();
        lblTelefon = new javax.swing.JLabel();
        ftxtTelefon = new javax.swing.JFormattedTextField();
        lblSifreTekrar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaAdres = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblResim.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel1.add(lblResim, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 600));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 600));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCarpi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCarpi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCarpiMouseClicked(evt);
            }
        });
        jPanel2.add(lblCarpi, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 40, 30));

        lblKullaniciKayit.setBackground(new java.awt.Color(0, 0, 0));
        lblKullaniciKayit.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblKullaniciKayit.setText("Kullanıcı Kayıt");
        jPanel2.add(lblKullaniciKayit, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        lblTC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTC.setText("TC:");
        jPanel2.add(lblTC, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        lblCizgi.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblCizgi.setForeground(new java.awt.Color(0, 0, 0));
        lblCizgi.setText("_________________");
        jPanel2.add(lblCizgi, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        txtAd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtAd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAdKeyTyped(evt);
            }
        });
        jPanel2.add(txtAd, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 180, 30));

        lblAd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAd.setText("Ad:");
        jPanel2.add(lblAd, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        txtSoyad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSoyad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSoyadKeyTyped(evt);
            }
        });
        jPanel2.add(txtSoyad, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 180, 30));

        lblSifre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSifre.setText("Şifre:");
        jPanel2.add(lblSifre, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, -1, -1));

        lblDogumTarihi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDogumTarihi.setText("Doğum Tarihi:");
        jPanel2.add(lblDogumTarihi, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 180, 30));

        lblCinsiyet.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCinsiyet.setText("Cinsiyet:");
        jPanel2.add(lblCinsiyet, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, -1, -1));

        lblEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEmail.setText("Email:");
        jPanel2.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, -1, -1));

        rdbErkek.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rdbErkek.setText("Erkek");
        jPanel2.add(rdbErkek, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 60, 20));

        rdbKadin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rdbKadin.setText("Kadın");
        jPanel2.add(rdbKadin, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 60, -1));

        lblSoyad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSoyad.setText("Soyad:");
        jPanel2.add(lblSoyad, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        pswSifre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(pswSifre, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 180, 30));

        pswSifreTekrar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(pswSifreTekrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 180, 30));

        lblAdres.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAdres.setText("Adres:");
        jPanel2.add(lblAdres, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, -1, -1));

        btnTemizle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTemizle.setText("TEMİZLE");
        btnTemizle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTemizleActionPerformed(evt);
            }
        });
        jPanel2.add(btnTemizle, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 530, 120, 30));

        btnKaydet.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnKaydet.setText("KAYDET");
        btnKaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKaydetActionPerformed(evt);
            }
        });
        jPanel2.add(btnKaydet, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 530, 120, 30));

        try {
            ftxtTC.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2.add(ftxtTC, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 180, 30));

        try {
            ftxtDogumTarihi.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2.add(ftxtDogumTarihi, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 180, 30));

        lblTelefon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTelefon.setText("Telefon:");
        jPanel2.add(lblTelefon, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        try {
            ftxtTelefon.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("+90(###)-###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2.add(ftxtTelefon, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 180, 30));

        lblSifreTekrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSifreTekrar.setText("Şifre Tekrar:");
        jPanel2.add(lblSifreTekrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, -1, -1));

        txtaAdres.setColumns(16);
        txtaAdres.setRows(5);
        jScrollPane1.setViewportView(txtaAdres);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, 180, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 480, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblCarpiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCarpiMouseClicked
        LoginGUI login = new LoginGUI();
        login.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblCarpiMouseClicked

    private void btnTemizleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTemizleActionPerformed
        // TODO add your handling code here:
        txtAd.setText("");
        txtSoyad.setText("");
        txtEmail.setText("");
        pswSifre.setText("");
        pswSifreTekrar.setText("");
        ftxtTC.setText("");
        ftxtTelefon.setText("");
        ftxtDogumTarihi.setText("");
        txtaAdres.setText("");
    }//GEN-LAST:event_btnTemizleActionPerformed

    private void btnKaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKaydetActionPerformed
        // TODO add your handling code here:
        String cinsiyet;
        char[] password1 = pswSifre.getPassword();
        String passwordString = new String(password1);
        if (rdbErkek.isSelected()) {
            cinsiyet = "E";
        } else {
            cinsiyet = "K";
        }
        Connection connection = null;
        DbHelper dbHelper = new DbHelper();
        PreparedStatement statement = null;
        boolean control = kontrol();
        if (control) {
            try {
                connection = dbHelper.getConnection();
                String sql = "insert into kullanicilar(tc_kimlik,ad,soyad,dogum_tarihi,cinsiyet,telefon,email,adres,sifre,hatali_giris) values (?,?,?,?,?,?,?,?,?,?)";
                statement = connection.prepareStatement(sql);
                statement.setString(1, ftxtTC.getText());
                statement.setString(2, txtAd.getText());
                statement.setString(3, txtSoyad.getText());
                statement.setString(4, login.formattedDate(ftxtDogumTarihi.getText()));
                statement.setString(5, cinsiyet);
                statement.setString(6, ftxtTelefon.getText());
                statement.setString(7, txtEmail.getText());
                statement.setString(8, txtaAdres.getText());
                statement.setString(9, passwordString);
                statement.setInt(10, 0);
                btnTemizleActionPerformed(evt);
                statement.executeUpdate();
                JOptionPane.showMessageDialog(rootPane, "Kayıt İşlemi Başarılı!");
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(rootPane, "Tüm Alanları Doğru Giriniz!");
            } finally {
                try {
                    statement.close();
                    connection.close();
                } catch (SQLException ex) {
                }
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Tüm Alanları Doldurunuz!");
        }


    }//GEN-LAST:event_btnKaydetActionPerformed

    private void txtAdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAdKeyTyped
        // TODO add your handling code here:
        char testChar = evt.getKeyChar();
        if (!(Character.isAlphabetic(testChar)))
            evt.consume();
    }//GEN-LAST:event_txtAdKeyTyped

    private void txtSoyadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSoyadKeyTyped
        // TODO add your handling code here:
        char testChar = evt.getKeyChar();
        if (!(Character.isAlphabetic(testChar)))
            evt.consume();
    }//GEN-LAST:event_txtSoyadKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewUserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewUserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewUserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewUserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewUserGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKaydet;
    private javax.swing.JButton btnTemizle;
    private javax.swing.JFormattedTextField ftxtDogumTarihi;
    private javax.swing.JFormattedTextField ftxtTC;
    private javax.swing.JFormattedTextField ftxtTelefon;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAd;
    private javax.swing.JLabel lblAdres;
    private javax.swing.JLabel lblCarpi;
    private javax.swing.JLabel lblCinsiyet;
    private javax.swing.JLabel lblCizgi;
    private javax.swing.JLabel lblDogumTarihi;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblKullaniciKayit;
    private javax.swing.JLabel lblResim;
    private javax.swing.JLabel lblSifre;
    private javax.swing.JLabel lblSifreTekrar;
    private javax.swing.JLabel lblSoyad;
    private javax.swing.JLabel lblTC;
    private javax.swing.JLabel lblTelefon;
    private javax.swing.JPasswordField pswSifre;
    private javax.swing.JPasswordField pswSifreTekrar;
    private javax.swing.JRadioButton rdbErkek;
    private javax.swing.JRadioButton rdbKadin;
    private javax.swing.JTextField txtAd;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtSoyad;
    private javax.swing.JTextArea txtaAdres;
    // End of variables declaration//GEN-END:variables
}
