/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hospital;

import classes.DbHelper;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DUMAN
 */
public class ReportGUI extends javax.swing.JFrame {

    /**
     * Creates new form ReportGUI
     */
    DefaultTableModel model;
    int bolumId;
    AppointmentGUI appointment = new AppointmentGUI();
    DoctorGUI doctor = new DoctorGUI();
    LoginGUI login = new LoginGUI();

    public ReportGUI() {
        initComponents();
        resimDuzelt(lblCarpi, "Images/carpiIcon.png");
        resimDuzelt(lblResim, "Images/reportIcon.png");
        model = (DefaultTableModel) tblKayitlar.getModel();
        loadBolum();
    }

    public void resimDuzelt(JLabel label, String url) {
        ImageIcon icon = new ImageIcon(getClass().getResource("/" + url));
        Image resim = icon.getImage();
        Image yeniResim = resim.getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon yeniIcon = new ImageIcon(yeniResim);
        label.setIcon(yeniIcon);
    }
    
    public void loadBolum() {
        Connection connection = null;
        DbHelper helper = new DbHelper();
        Statement statement = null;
        ResultSet resultSet;
        ArrayList<String> bolumler = null;
        try {
            connection = helper.getConnection();
            statement = connection.createStatement();
            resultSet = statement.executeQuery("select * from bolumler");
            bolumler = new ArrayList<String>();
            while (resultSet.next()) {
                bolumler.add((resultSet.getString("bolum_adi")));
            }
            for (String bolum : bolumler) {
                cmbBolum.addItem(bolum);
            }
        } catch (SQLException exception) {
            helper.showErrorMessage(exception);
        } finally {
            try {
                statement.close();
                connection.close();
            } catch (SQLException ex) {
            }
        }
    }
    
    public void loadDoktor() {
        cmbDoktor.removeAllItems();
        bolumId = doctor.bolumId((String) cmbBolum.getSelectedItem());
        ArrayList<String> doctorlar;
        try {
            doctorlar = getDoctors();
            for (String str : doctorlar) {
                cmbDoktor.addItem(str);
            }
        } catch (SQLException ex) {
            System.out.println(ex.getErrorCode());
        }
    }
    
    public ArrayList<String> getDoctors() throws SQLException {
        Connection connection = null;
        DbHelper helper = new DbHelper();
        Statement statement = null;
        ResultSet resultSet;
        ArrayList<String> doctors = null;
        try {
            connection = helper.getConnection();
            statement = connection.createStatement();
            resultSet = statement.executeQuery("select * from doktorlar where bolum_id = " + bolumId);
            doctors = new ArrayList<String>();
            while (resultSet.next()) {
                String isim = resultSet.getString("ad") + " " + resultSet.getString("soyad");
                doctors.add(isim);
            }
        } catch (SQLException e) {
            helper.showErrorMessage(e);
        } finally {
            statement.close();
            connection.close();
        }
        return doctors;
    }

    public String control() {
        String sql = "select * from v_randevular where 1 = 1";
        if (!ftxtHastaTC.getText().equals("           ")) {
            sql += " and hasta_id = " + appointment.hastaId(ftxtHastaTC.getText());
        }
        if (!cmbBolum.getSelectedItem().equals("Hepsi")) {
            sql += " and bolum_id = " + doctor.bolumId((String) cmbBolum.getSelectedItem());
        }
        if (!cmbDoktor.getSelectedItem().equals("Hepsi")) {
            sql += " and doktor_adsoyad = '" + (String) cmbDoktor.getSelectedItem()+"'";
        }
        if (!ftxtBaslangicTarihi.getText().equals("  -  -    ")) {
            sql += " and tarih >= '" + login.formattedDate(ftxtBaslangicTarihi.getText())+"'";
        }
        if (!ftxtBitisTarihi.getText().equals("  -  -    ")) {
            sql += " and tarih <= '" + login.formattedDate(ftxtBitisTarihi.getText())+"'";
        }
        return sql;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblCarpi = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKayitlar = new javax.swing.JTable();
        lblResim = new javax.swing.JLabel();
        lblHastaTC = new javax.swing.JLabel();
        lblCizgi = new javax.swing.JLabel();
        lblHastaBilgileri = new javax.swing.JLabel();
        lblBolum = new javax.swing.JLabel();
        lblBaslangicTarihi = new javax.swing.JLabel();
        lblBitisTarihi = new javax.swing.JLabel();
        btnListele = new javax.swing.JButton();
        cmbBolum = new javax.swing.JComboBox<>();
        cmbDoktor = new javax.swing.JComboBox<>();
        lblDoktor = new javax.swing.JLabel();
        ftxtBitisTarihi = new javax.swing.JFormattedTextField();
        ftxtHastaTC = new javax.swing.JFormattedTextField();
        ftxtBaslangicTarihi = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCarpi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCarpi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCarpiMouseClicked(evt);
            }
        });
        jPanel1.add(lblCarpi, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, 40, 30));

        jScrollPane1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        tblKayitlar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Doktor Adı", "Hasta Adı", "Bölüm", "Randevu Tarihi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblKayitlar.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblKayitlar);
        if (tblKayitlar.getColumnModel().getColumnCount() > 0) {
            tblKayitlar.getColumnModel().getColumn(0).setResizable(false);
            tblKayitlar.getColumnModel().getColumn(1).setResizable(false);
            tblKayitlar.getColumnModel().getColumn(2).setResizable(false);
            tblKayitlar.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 810, 220));
        jPanel1.add(lblResim, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, 180, 190));

        lblHastaTC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblHastaTC.setText("Hasta TC:");
        lblHastaTC.setToolTipText("");
        jPanel1.add(lblHastaTC, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        lblCizgi.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblCizgi.setText("_________________");
        jPanel1.add(lblCizgi, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        lblHastaBilgileri.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblHastaBilgileri.setText("Rapor Bilgileri");
        jPanel1.add(lblHastaBilgileri, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        lblBolum.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBolum.setText("Bölüm:");
        lblBolum.setToolTipText("");
        jPanel1.add(lblBolum, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        lblBaslangicTarihi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBaslangicTarihi.setText("Başlangıç Tarihi:");
        lblBaslangicTarihi.setToolTipText("");
        jPanel1.add(lblBaslangicTarihi, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, -1, -1));

        lblBitisTarihi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBitisTarihi.setText("Bitiş Tarihi:");
        lblBitisTarihi.setToolTipText("");
        jPanel1.add(lblBitisTarihi, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, -1, -1));

        btnListele.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnListele.setText("Listele");
        btnListele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListeleActionPerformed(evt);
            }
        });
        jPanel1.add(btnListele, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 180, 30));

        cmbBolum.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hepsi" }));
        cmbBolum.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbBolumİtemStateChanged(evt);
            }
        });
        jPanel1.add(cmbBolum, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 180, 30));

        cmbDoktor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hepsi" }));
        jPanel1.add(cmbDoktor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 180, 30));

        lblDoktor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDoktor.setText("Doktor:");
        lblDoktor.setToolTipText("");
        jPanel1.add(lblDoktor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        try {
            ftxtBitisTarihi.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(ftxtBitisTarihi, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 180, 30));

        try {
            ftxtHastaTC.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(ftxtHastaTC, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 180, 30));

        try {
            ftxtBaslangicTarihi.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(ftxtBaslangicTarihi, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 180, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblCarpiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCarpiMouseClicked
        MenuGUI menu = new MenuGUI();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblCarpiMouseClicked

    private void btnListeleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListeleActionPerformed
        // TODO add your handling code here:
        Connection connection = null;
        DbHelper helper = new DbHelper();
        PreparedStatement statement = null;
        ResultSet resultSet;
        model.setRowCount(0);
        try {
            connection = helper.getConnection();
            statement = connection.prepareStatement(control());
            resultSet = statement.executeQuery();
            while (resultSet.next()) {
                Object[] row = {resultSet.getString("doktor_adsoyad"), resultSet.getString("hasta_adsoyad"), resultSet.getString("bolum_adi"), login.getirFormattedDate(resultSet.getString("tarih"))};
                model.addRow(row);
            }
        } catch (SQLException e) {
            helper.showErrorMessage(e);
        } finally {
            try {
                statement.close();
                connection.close();
            } catch (SQLException ex) {
            }
        }
        ftxtBaslangicTarihi.setText("");
        ftxtBitisTarihi.setText("");
    }//GEN-LAST:event_btnListeleActionPerformed

    private void cmbBolumİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbBolumİtemStateChanged
        // TODO add your handling code here:
        if (cmbBolum.getSelectedItem() == "Hepsi") {
            cmbDoktor.removeAllItems();
            cmbDoktor.addItem("Hepsi");
        }else{
            loadDoktor();
        }
        
    }//GEN-LAST:event_cmbBolumİtemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnListele;
    private javax.swing.JComboBox<String> cmbBolum;
    private javax.swing.JComboBox<String> cmbDoktor;
    private javax.swing.JFormattedTextField ftxtBaslangicTarihi;
    private javax.swing.JFormattedTextField ftxtBitisTarihi;
    private javax.swing.JFormattedTextField ftxtHastaTC;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBaslangicTarihi;
    private javax.swing.JLabel lblBitisTarihi;
    private javax.swing.JLabel lblBolum;
    private javax.swing.JLabel lblCarpi;
    private javax.swing.JLabel lblCizgi;
    private javax.swing.JLabel lblDoktor;
    private javax.swing.JLabel lblHastaBilgileri;
    private javax.swing.JLabel lblHastaTC;
    private javax.swing.JLabel lblResim;
    private javax.swing.JTable tblKayitlar;
    // End of variables declaration//GEN-END:variables
}
